---
title: 'AedesTraits: a global dataset of temperature–dependent trait responses in *Aedes* mosquitoes'
date: '2025-12-22'
author:
- name: D. Da Re
- name: V. Andreo
- name: T. V. San Miguel
- name: M. Blaha
- name: R. Rosa
- name: A. Rizzoli
- name: J. Harrison
- name: S. Sorek
- name: L. Johnson
- name: P. Huxley
pub-type: Journal article
doi: 10.1038/s41597-025-06461-z
categories:
- Mosquitoes
- Arboviruses
- Climate
---

[PDF](https://doi.org/10.1038/s41597-025-06461-z)

## Abstract

Invasive *Aedes* mosquitoes are major vectors of arboviral diseases such as dengue, Zika, and chikungunya, posing an increasing threat to global public health. Their recent geographic expansion calls for predictive models to simulate population dynamics and transmission risk. Temperature is a key driver in these models, influencing traits that affect vector competence. Numerous datasets on temperature-dependent traits exist for *Aedes aegypti* and *Aedes albopictus*, though they are scattered, inconsistent, and difficult to synthesise. For emerging species like *Aedes japonicus* and *Aedes koreicus*, such datasets are scarce. To address these gaps, we developed AedesTraits, an open-access, machine-readable dataset aligned with VecTraits standards. It compiles and systematises experimental data on temperature-dependent traits across these four *Aedes* species, covering life-history, morphological, physiological, and behavioural traits. Our synthesis highlights existing knowledge gaps and identifies under-studied species and traits. By promoting data systematisation and accessibility, AedesTraits supports *Aedes*–borne disease modelling and fosters international collaboration in the development of forecasting tools for arbovirus outbreaks.

## Citation

D. Da Re, V. Andreo, T. V. San Miguel, M. Blaha, R. Rosa, A. Rizzoli, et al. (2025). AedesTraits: a global dataset of temperature–dependent trait responses in *Aedes* mosquitoes. *Scientific Data, 12, 2033.*. <https://doi.org/10.1038/s41597-025-06461-z>
